service: picq-backend

plugins:
  - serverless-prune-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  stage: dev
  environment:
    STAGE: ${self:custom.currentStage}
    ORIGIN_WHITELIST: ${file(./config/config.${self:custom.currentStage}.json):ORIGIN_WHITELIST}
    MONGO_DB_URL: ${file(./config/config.${self:custom.currentStage}.json):MONGO_DB_URL}
    S3_BUCKET_NAME: ${file(./config/config.${self:custom.currentStage}.json):S3_BUCKET_NAME}
    PLIVO_AUTH_ID: ${file(./config/config.${self:custom.currentStage}.json):PLIVO_AUTH_ID}
    PLIVO_AUTH_TOKEN: ${file(./config/config.${self:custom.currentStage}.json):PLIVO_AUTH_TOKEN}
    FIREBASE_PROJECT_ID: ${file(./config/config.${self:custom.currentStage}.json):FIREBASE_PROJECT_ID}
    FIREBASE_PRIVATE_KEY_ID: ${file(./config/config.${self:custom.currentStage}.json):FIREBASE_PRIVATE_KEY_ID}
    FIREBASE_PRIVATE_KEY: ${file(./config/config.${self:custom.currentStage}.json):FIREBASE_PRIVATE_KEY}
    FIREBASE_CLIENT_EMAIL: ${file(./config/config.${self:custom.currentStage}.json):FIREBASE_CLIENT_EMAIL}
    FIREBASE_CLIENT_ID: ${file(./config/config.${self:custom.currentStage}.json):FIREBASE_CLIENT_ID}
    FIREBASE_AUTH_URI: ${file(./config/config.${self:custom.currentStage}.json):FIREBASE_AUTH_URI}
    FIREBASE_TOKEN_URI: ${file(./config/config.${self:custom.currentStage}.json):FIREBASE_TOKEN_URI}
    FIREBASE_AUTH_PROVIDER_X509_CERT_URL: ${file(./config/config.${self:custom.currentStage}.json):FIREBASE_AUTH_PROVIDER_X509_CERT_URL}
    FIREBASE_CLIENT_X509_CERT_URL: ${file(./config/config.${self:custom.currentStage}.json):FIREBASE_CLIENT_X509_CERT_URL}
    RAZORPAY_KEY_ID: ${file(./config/config.${self:custom.currentStage}.json):RAZORPAY_KEY_ID}
    RAZORPAY_KEY_SECRET: ${file(./config/config.${self:custom.currentStage}.json):RAZORPAY_KEY_SECRET}
    RAZORPAY_ACCOUNT_NUMBER: ${file(./config/config.${self:custom.currentStage}.json):RAZORPAY_ACCOUNT_NUMBER}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "picq"
            - "/*"

custom:
  prune:
    automatic: true
    number: 1
  serverless-offline:
    httpPort: 4000
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}

  # you can overwrite defaults here
  stage: ${self:custom.currentStage}

package:
  exclude:
    - "venv/**"

functions:
  auth:
    handler: ./handlers/auth.handler
    events:
      - http:
          path: /ping
          method: GET
          cors: true
      - http:
          path: /signup
          method: POST
          cors: true
      - http:
          path: /signin
          method: POST
          cors: true
      - http:
          path: /auth_otp
          method: POST
          cors: true
      - http:
          path: /auth_verify
          method: POST
          cors: true
      - http:
          path: /auth_google
          method: POST
          cors: true
      - http:
          path: /onboarding
          method: POST
          cors: true
  token:
    handler: ./handlers/token.handler
    events:
      - http:
          path: /accessToken
          method: POST
          cors: true
  main:
    handler: ./handlers/main.handler
    events:
      - http:
          path: /main
          method: GET
          cors: true
  user:
    handler: ./handlers/user.handler
    events:
      - http:
          path: /users
          method: GET
          cors: true
      - http:
          path: /user
          method: GET
          cors: true
      - http:
          path: /user
          method: PUT
          cors: true
      - http:
          path: /user/premier
          method: PUT
          cors: true
      - http:
          path: /favourite
          method: PUT
          cors: true
      - http:
          path: /user/reviews
          method: GET
          cors: true
  admin:
    handler: ./handlers/admin.handler
    events:
      - http:
          path: /admins
          method: POST
          cors: true
      - http:
          path: /admins
          method: GET
          cors: true
      - http:
          path: /admins/{id}
          method: PUT
          cors: true
      - http:
          path: /admins/{id}
          method: DELETE
          cors: true
  address:
    handler: ./handlers/address.handler
    events:
      - http:
          path: /address
          method: POST
          cors: true
      - http:
          path: /address/{addressID}
          method: GET
          cors: true
      - http:
          path: /address/{addressID}
          method: PUT
          cors: true
      - http:
          path: /address/{addressID}
          method: DELETE
          cors: true
  file:
    handler: ./handlers/file.handler
    events:
      - http:
          path: /upload
          method: POST
          cors: true
      - http:
          path: /upload/batch
          method: POST
          cors: true
  documents:
    handler: ./handlers/documents.handler
    events:
      - http:
          path: /documents
          method: POST
          cors: true
      - http:
          path: /documents/{documentID}
          method: PUT
          cors: true
  bookings:
    handler: ./handlers/bookings.handler
    events:
      - http:
          path: /bookings/order
          method: POST
          cors: true
      - http:
          path: /bookings
          method: POST
          cors: true
      - http:
          path: /bookings/offline
          method: POST
          cors: true
      - http:
          path: /bookings/offline/{id}
          method: PUT
          cors: true
      - http:
          path: /bookings
          method: GET
          cors: true
      - http:
          path: /bookings/{id}
          method: PUT
          cors: true
      - http:
          path: /bookings/{id}
          method: GET
          cors: true
      - http:
          path: /bookings/{id}/refund
          method: POST
          cors: true
      - http:
          path: /bookings/{id}/cancel
          method: POST
          cors: true
  coupons:
    handler: ./handlers/coupons.handler
    events:
      - http:
          path: /coupons/me
          method: GET
          cors: true
      - http:
          path: /coupons/applicable
          method: GET
          cors: true
      - http:
          path: /coupons/code/{code}
          method: GET
          cors: true
      - http:
          path: /coupons
          method: GET
          cors: true
      - http:
          path: /coupons
          method: POST
          cors: true
      - http:
          path: /coupons/{id}
          method: PUT
          cors: true
      - http:
          path: /coupons/{id}
          method: DELETE
          cors: true
  studio:
    handler: ./handlers/studio.handler
    events:
      - http:
          path: /studios
          method: GET
          cors: true
      - http:
          path: /studios/featured
          method: GET
          cors: true
      - http:
          path: /studios/most-rated
          method: GET
          cors: true
      - http:
          path: /studios/search
          method: POST
          cors: true
      - http:
          path: /studios/favourites
          method: GET
          cors: true
      - http:
          path: /studio/{studioId}
          method: GET
          cors: true
      - http:
          path: /studio/{studioId}
          method: PUT
          cors: true
      - http:
          path: /studio/{studioId}/room
          method: POST
          cors: true
      - http:
          path: /studio/{studioId}/room/{roomId}
          method: PUT
          cors: true
      - http:
          path: /studio/{studioId}/room/{roomId}
          method: DELETE
          cors: true
      - http:
          path: /studio/{studioId}/review
          method: POST
          cors: true
      - http:
          path: /studio/{studioId}/review
          method: GET
          cors: true
  otp:
    handler: ./handlers/otp.handler
    events:
      - http:
          path: /send_otp
          method: POST
          cors: true
      - http:
          path: /verify_otp
          method: POST
          cors: true
  notification:
    handler: ./handlers/notification.handler
    events:
      - http:
          path: /notifications
          method: GET
          cors: true
      - http:
          path: /notifications/{id}
          method: GET
          cors: true
      - http:
          path: /notifications/{id}
          method: DELETE
          cors: true
      - http:
          path: /notifications/{id}/read
          method: PUT
          cors: true
      - http:
          path: /save-fcm
          method: POST
          cors: true
  payouts:
    handler: ./handlers/payouts.handler
    events:
      - http:
          path: /payouts
          method: GET
          cors: true
      - http:
          path: /payouts/request
          method: POST
          cors: true
      - http:
          path: /payouts/settle
          method: PUT
          cors: true